name: Prevent Non-Release PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the source branch is a release branch
        run: |
          if [[ "${{ github.head_ref }}" != release/* ]]; then
            echo "Only release branches can be merged into the main branch."
            exit 1
          fi